# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainsys.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 854)
        MainWindow.setStyleSheet("/*Style for Student Info Input*/\n"
"#inputFrame1 QLineEdit{\n"
"    padding: 4px, 5px;\n"
"    border: 1px solid #838383;\n"
"     background: #fbfbfb;\n"
"}\n"
"#inputFrame1 QLineEdit:focus, #inputFram1 QComboBox:focus{\n"
"      border: 1.5px solid #000;\n"
"}\n"
"\n"
"#inputFrame1, QComboBox{\n"
"    padding: 4px, 5px;\n"
"    border: 1px solid #838383;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"#inputFrame1{\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*Style for Course Info Input*/\n"
"#inputFrame2{\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#inputFrame2 QLineEdit{\n"
"    padding: 4px, 5px;\n"
"    border: 1px solid #838383;\n"
"     background: #fbfbfb;\n"
"}\n"
"#inputFrame2 QLineEdit:focus, #inputFrame2 QComboBox:focus{\n"
"      border: 1.5px solid #000;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*Style for search frames*/\n"
"#searchFrame QLineEdit, \n"
"#searchFrame QComboBox{\n"
"    padding: 4px, 5px;\n"
"    border: 1px solid #838383;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"#searchFrame2 QLineEdit {\n"
"    padding: 4px, 5px;\n"
"    border: 1px solid #838383;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"#searchFrame QLineEdit:focus, #searchFrame QComboBox:focus{\n"
"    border: 1.5px solid #000;\n"
"}\n"
"\n"
"#searchFrame2 QLineEdit:focus{\n"
"    border: 1.5px solid #000;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*Style for ComboBoxes*/\n"
"QComboBox::drop-down{\n"
"    background:transparent;\n"
"    border: none;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    image:url(:/styles/icon/dropdown.svg);\n"
"}\n"
"\n"
"/*Style for tables*/\n"
"QTableWidget{\n"
"    border-radius: 3px;\n"
"    border: 1px solid #f0f0f0;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    border: none;\n"
"    border-bottom: 1px solid #d0c6ff;\n"
"    text-align: left;\n"
"    padding: 3px 5px;\n"
"}\n"
"\n"
"QTableWidget::Item{\n"
"    border-bottom: 1px solid #d0c6ff;\n"
"    color: #000;\n"
"    padding-left: 3px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.studentDisplay = QtWidgets.QTableWidget(self.centralwidget)
        self.studentDisplay.setGeometry(QtCore.QRect(10, 260, 901, 581))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.studentDisplay.setFont(font)
        self.studentDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.studentDisplay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.studentDisplay.setShowGrid(False)
        self.studentDisplay.setObjectName("studentDisplay")
        self.studentDisplay.setColumnCount(5)
        self.studentDisplay.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.studentDisplay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.studentDisplay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.studentDisplay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentDisplay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentDisplay.setHorizontalHeaderItem(4, item)
        self.studentDisplay.horizontalHeader().setDefaultSectionSize(180)
        self.studentDisplay.horizontalHeader().setStretchLastSection(False)
        self.studentDisplay.verticalHeader().setHighlightSections(True)
        self.studentDisplay.verticalHeader().setSortIndicatorShown(False)
        self.studentDisplay.verticalHeader().setStretchLastSection(False)
        self.searchFrame = QtWidgets.QFrame(self.centralwidget)
        self.searchFrame.setGeometry(QtCore.QRect(10, 220, 901, 41))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.searchStudentLabel = QtWidgets.QLabel(self.searchFrame)
        self.searchStudentLabel.setGeometry(QtCore.QRect(260, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.searchStudentLabel.setFont(font)
        self.searchStudentLabel.setObjectName("searchStudentLabel")
        self.searchFilterLabel = QtWidgets.QLabel(self.searchFrame)
        self.searchFilterLabel.setGeometry(QtCore.QRect(20, 10, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.searchFilterLabel.setFont(font)
        self.searchFilterLabel.setObjectName("searchFilterLabel")
        self.searchStudent = QtWidgets.QLineEdit(self.searchFrame)
        self.searchStudent.setGeometry(QtCore.QRect(370, 10, 521, 27))
        self.searchStudent.setStyleSheet("#searchStudent:focus{\n"
"    border: 1.5px solid #000;\n"
"}\n"
"\n"
"")
        self.searchStudent.setObjectName("searchStudent")
        self.searchFilter = QtWidgets.QComboBox(self.searchFrame)
        self.searchFilter.setGeometry(QtCore.QRect(110, 10, 131, 27))
        self.searchFilter.setObjectName("searchFilter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.courseDisplay = QtWidgets.QTableWidget(self.centralwidget)
        self.courseDisplay.setGeometry(QtCore.QRect(930, 260, 391, 581))
        self.courseDisplay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.courseDisplay.setShowGrid(False)
        self.courseDisplay.setObjectName("courseDisplay")
        self.courseDisplay.setColumnCount(2)
        self.courseDisplay.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.courseDisplay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.courseDisplay.setHorizontalHeaderItem(1, item)
        self.courseDisplay.horizontalHeader().setDefaultSectionSize(150)
        self.courseDisplay.horizontalHeader().setStretchLastSection(True)
        self.inputFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.inputFrame1.setGeometry(QtCore.QRect(10, 60, 891, 151))
        self.inputFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputFrame1.setObjectName("inputFrame1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.inputFrame1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 10, 341, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.idInput2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.idInput2.setObjectName("idInput2")
        self.gridLayout.addWidget(self.idInput2, 0, 2, 1, 1)
        self.yearLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yearLabel.setFont(font)
        self.yearLabel.setObjectName("yearLabel")
        self.gridLayout.addWidget(self.yearLabel, 2, 0, 1, 1)
        self.idInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.idInput.setObjectName("idInput")
        self.gridLayout.addWidget(self.idInput, 0, 1, 1, 1)
        self.IDLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IDLabel.setFont(font)
        self.IDLabel.setObjectName("IDLabel")
        self.gridLayout.addWidget(self.IDLabel, 0, 0, 1, 1)
        self.nameInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nameInput.setText("")
        self.nameInput.setObjectName("nameInput")
        self.gridLayout.addWidget(self.nameInput, 1, 1, 1, 2)
        self.yearCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.yearCombo.setFont(font)
        self.yearCombo.setObjectName("yearCombo")
        self.gridLayout.addWidget(self.yearCombo, 2, 1, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.inputFrame1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(410, 10, 331, 103))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.gridLayoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.courseLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.courseLabel.setFont(font)
        self.courseLabel.setObjectName("courseLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.courseLabel)
        self.courseCombo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.courseCombo.setFont(font)
        self.courseCombo.setObjectName("courseCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.courseCombo)
        self.genderLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.genderCombo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.genderCombo.setFont(font)
        self.genderCombo.setObjectName("genderCombo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.genderCombo)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.inputFrame1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(770, 10, 101, 128))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addStudent = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.addStudent.setFont(font)
        self.addStudent.setStyleSheet("#addStudent{\n"
"                    cursor: pointer;\n"
"                    background-color: #007a5a;\n"
"                    height: 30px;\n"
"                    border: 1px solid #007a5a;\n"
"                    border-radius:4px;\n"
"                    color: #fff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"         #addStudent:hover {\n"
"                        background-color: rgb(0, 170, 127);  \n"
"                    } \n"
"                \n"
" \n"
"                ")
        self.addStudent.setObjectName("addStudent")
        self.verticalLayout.addWidget(self.addStudent)
        self.editStudent = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.editStudent.setFont(font)
        self.editStudent.setStyleSheet("#editStudent{\n"
"                    cursor: pointer;\n"
"                    background-color:rgb(15, 119, 255);\n"
"                    height: 30px;\n"
"                    border: 1px solid rgb(15, 119, 255);\n"
"                    border-radius:4px;\n"
"                    color: #ffffff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"#editStudent:hover {\n"
"         background-color:rgb(0, 166, 255); \n"
"                    } \n"
"                ")
        self.editStudent.setObjectName("editStudent")
        self.verticalLayout.addWidget(self.editStudent)
        self.deleteStudent = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.deleteStudent.setFont(font)
        self.deleteStudent.setStyleSheet("#deleteStudent{\n"
"                    cursor: pointer;\n"
"                    background-color: rgb(255, 61, 61);\n"
"                    height: 30px;\n"
"                    border: 1px solid rgb(255, 32, 32);\n"
"                    border-radius:4px;\n"
"                    color: #fff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"#deleteStudent:hover {\n"
"                     background-color: rgb(255, 32, 32);  \n"
"                    } \n"
"                \n"
" ")
        self.deleteStudent.setObjectName("deleteStudent")
        self.verticalLayout.addWidget(self.deleteStudent)
        self.inputFrame2 = QtWidgets.QFrame(self.centralwidget)
        self.inputFrame2.setGeometry(QtCore.QRect(920, 60, 401, 151))
        self.inputFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputFrame2.setLineWidth(1)
        self.inputFrame2.setObjectName("inputFrame2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.inputFrame2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 10, 101, 128))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addCourse = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.addCourse.setFont(font)
        self.addCourse.setStyleSheet("#addCourse{\n"
"                    cursor: pointer;\n"
"                    background-color: #007a5a;\n"
"                    height: 30px;\n"
"                    border: 1px solid #007a5a;\n"
"                    border-radius:4px;\n"
"                    color: #fff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"         #addCourse:hover {\n"
"                        background-color: rgb(0, 170, 127);  \n"
"                    } \n"
"                \n"
" \n"
"                ")
        self.addCourse.setObjectName("addCourse")
        self.verticalLayout_2.addWidget(self.addCourse)
        self.editCourse = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.editCourse.setFont(font)
        self.editCourse.setStyleSheet("#editCourse{\n"
"              cursor: pointer;\n"
"                    background-color:rgb(15, 119, 255);\n"
"                    height: 30px;\n"
"                    border: 1px solid rgb(15, 119, 255);\n"
"                    border-radius:4px;\n"
"                    color: #ffffff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"#editCourse:hover {\n"
"         background-color:rgb(0, 166, 255); \n"
"                    } \n"
"                \n"
"                ")
        self.editCourse.setObjectName("editCourse")
        self.verticalLayout_2.addWidget(self.editCourse)
        self.deleteCourse = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.deleteCourse.setFont(font)
        self.deleteCourse.setStyleSheet("#deleteCourse{\n"
"                    cursor: pointer;\n"
"                    background-color: rgb(255, 61, 61);\n"
"                    height: 30px;\n"
"                    border: 1px solid rgb(255, 32, 32);\n"
"                    border-radius:4px;\n"
"                    color: #fff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"#deleteCourse:hover {\n"
"                     background-color: rgb(255, 32, 32);  \n"
"                    } \n"
"                \n"
" ")
        self.deleteCourse.setObjectName("deleteCourse")
        self.verticalLayout_2.addWidget(self.deleteCourse)
        self.layoutWidget = QtWidgets.QWidget(self.inputFrame2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 120))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.coursecodeLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.coursecodeLabel.setFont(font)
        self.coursecodeLabel.setObjectName("coursecodeLabel")
        self.gridLayout_2.addWidget(self.coursecodeLabel, 0, 0, 1, 1)
        self.courseCodeInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.courseCodeInput.setObjectName("courseCodeInput")
        self.gridLayout_2.addWidget(self.courseCodeInput, 1, 0, 1, 1)
        self.courseNameInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.courseNameInput.setText("")
        self.courseNameInput.setObjectName("courseNameInput")
        self.gridLayout_2.addWidget(self.courseNameInput, 3, 0, 1, 1)
        self.coursenameLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.coursenameLabel.setFont(font)
        self.coursenameLabel.setObjectName("coursenameLabel")
        self.gridLayout_2.addWidget(self.coursenameLabel, 2, 0, 1, 1)
        self.searchFrame2 = QtWidgets.QFrame(self.centralwidget)
        self.searchFrame2.setGeometry(QtCore.QRect(930, 220, 391, 41))
        self.searchFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame2.setObjectName("searchFrame2")
        self.searchCourseLabel = QtWidgets.QLabel(self.searchFrame2)
        self.searchCourseLabel.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.searchCourseLabel.setFont(font)
        self.searchCourseLabel.setObjectName("searchCourseLabel")
        self.searchCourse = QtWidgets.QLineEdit(self.searchFrame2)
        self.searchCourse.setGeometry(QtCore.QRect(120, 10, 261, 27))
        self.searchCourse.setObjectName("searchCourse")
        self.clearStudent = QtWidgets.QPushButton(self.centralwidget)
        self.clearStudent.setGeometry(QtCore.QRect(780, 20, 99, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.clearStudent.setFont(font)
        self.clearStudent.setStyleSheet("#clearStudent{\n"
"                    cursor: pointer;\n"
"                    background-color: rgb(56, 56, 56);\n"
"                    height: 30px;\n"
"                    border: 1px solid rgb(56, 56, 56);\n"
"                    border-radius:4px;\n"
"                    color: #fff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"         #clearStudent:hover {\n"
"                        background-color: rgb(68, 68, 68);  \n"
"                    } \n"
"                \n"
" \n"
"                ")
        self.clearStudent.setObjectName("clearStudent")
        self.clearCourse = QtWidgets.QPushButton(self.centralwidget)
        self.clearCourse.setGeometry(QtCore.QRect(1210, 20, 99, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.clearCourse.setFont(font)
        self.clearCourse.setStyleSheet("#clearCourse{\n"
"                    cursor: pointer;\n"
"                    background-color: rgb(56, 56, 56);\n"
"                    height: 30px;\n"
"                    border: 1px solid rgb(56, 56, 56);\n"
"                    border-radius:4px;\n"
"                    color: #fff;\n"
"                    font-size: 13px;\n"
"                    line-height: 30px;\n"
"                    text-align: center;\n"
"}\n"
"         #clearCourse:hover {\n"
"                        background-color: rgb(68, 68, 68);  \n"
"                    } \n"
"                ")
        self.clearCourse.setObjectName("clearCourse")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.studentDisplay.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Number"))
        item = self.studentDisplay.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.studentDisplay.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Year Level"))
        item = self.studentDisplay.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.studentDisplay.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Course Code"))
        self.searchStudentLabel.setText(_translate("MainWindow", "Search Student:"))
        self.searchFilterLabel.setText(_translate("MainWindow", "Search by:"))
        self.label.setText(_translate("MainWindow", "Student Information System"))
        item = self.courseDisplay.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Course Code"))
        item = self.courseDisplay.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Course Name"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.yearLabel.setText(_translate("MainWindow", "Year Level"))
        self.IDLabel.setText(_translate("MainWindow", "ID Number"))
        self.courseLabel.setText(_translate("MainWindow", "Course Code"))
        self.genderLabel.setText(_translate("MainWindow", "Gender"))
        self.addStudent.setText(_translate("MainWindow", "Add"))
        self.editStudent.setText(_translate("MainWindow", "Edit"))
        self.deleteStudent.setText(_translate("MainWindow", "Delete"))
        self.addCourse.setText(_translate("MainWindow", "Add"))
        self.editCourse.setText(_translate("MainWindow", "Edit"))
        self.deleteCourse.setText(_translate("MainWindow", "Delete"))
        self.coursecodeLabel.setText(_translate("MainWindow", "Course Code"))
        self.coursenameLabel.setText(_translate("MainWindow", "Course Name"))
        self.searchCourseLabel.setText(_translate("MainWindow", "Search Course:"))
        self.clearStudent.setText(_translate("MainWindow", "Clear"))
        self.clearCourse.setText(_translate("MainWindow", "Clear "))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
